### ISSUE TITLE
Calling pack on a model leads to "undefined method `eager` NoMethodError"

### ISSUE THREAD

**Issue by andrewjluo** [PaulJuliusMartinez/sequel-packer#1]
![image](https://user-images.githubusercontent.com/5866856/82165702-f4d86880-986a-11ea-8432-2848fd2ec12c.png)

**Comment by andrewjluo** [comment]
Usage:
`packer = Packers::TwitchUser.new(:streams)`

**Comment by andrewjluo** [comment]
Stacktrace:
```
2020-05-17 18:20:09 - NoMethodError - undefined method `eager' for #<Ribbon::Models::TwitchUser:0x00007fa8d9656880>:
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sequel-packer-0.2.0/lib/sequel/packer.rb:237:in `pack'
	/Users/andrew/projects/ribbon/controllers/api/channels.rb:12:in `block in <class:ChannelsController>'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `block in compile!'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (3 levels) in route!'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1006:in `route_eval'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (2 levels) in route!'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1035:in `block in process_route'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `catch'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `process_route'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:985:in `block in route!'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `each'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `route!'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1098:in `block in dispatch!'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1095:in `dispatch!'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `block in call!'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `call!'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:908:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-protection-2.0.8.1/lib/rack/protection/xss_header.rb:18:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-protection-2.0.8.1/lib/rack/protection/path_traversal.rb:16:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-protection-2.0.8.1/lib/rack/protection/json_csrf.rb:26:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-protection-2.0.8.1/lib/rack/protection/frame_options.rb:31:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.0.9/lib/rack/null_logger.rb:9:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.0.9/lib/rack/head.rb:12:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/show_exceptions.rb:22:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:194:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1951:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-protection-2.0.8.1/lib/rack/protection/xss_header.rb:18:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-protection-2.0.8.1/lib/rack/protection/path_traversal.rb:16:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-protection-2.0.8.1/lib/rack/protection/json_csrf.rb:26:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-protection-2.0.8.1/lib/rack/protection/frame_options.rb:31:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.0.9/lib/rack/session/abstract/id.rb:259:in `context'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.0.9/lib/rack/session/abstract/id.rb:253:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.0.9/lib/rack/lint.rb:49:in `_call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.0.9/lib/rack/lint.rb:37:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.0.9/lib/rack/show_exceptions.rb:23:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.0.9/lib/rack/common_logger.rb:33:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:231:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:86:in `proceed_as_child'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:31:in `call!'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:18:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/shotgun-0.9.2/lib/shotgun/favicon.rb:12:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/shotgun-0.9.2/lib/shotgun/static.rb:14:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.0.9/lib/rack/urlmap.rb:68:in `block in call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.0.9/lib/rack/urlmap.rb:53:in `each'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.0.9/lib/rack/urlmap.rb:53:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.0.9/lib/rack/builder.rb:153:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/configuration.rb:228:in `call'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/server.rb:682:in `handle_request'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/server.rb:472:in `process_client'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/server.rb:328:in `block in run'
	/Users/andrew/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.3/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Comment by andrewjluo** [comment]
Packer definition
```
    class TwitchUser < Sequel::Packer
      model Models::TwitchUser

      field :id
      field :twitch_id
      field :display_name
      field :handle, &:login
      field :broadcaster_type
      field :profile_image_url

      trait :streams do
        field :twitch_streams, Packers::TwitchStream
      end
    end
```

**Comment by PaulJuliusMartinez** [comment]
@andrewjluo, passing individual models to `#pack` wasn't added until [`v0.4.0`](https://github.com/PaulJuliusMartinez/sequel-packer/blob/master/CHANGELOG.md#040-2020-05-17), and it looks like you're still on `v0.2.0`.

Going to close this for now, but feel free to re-open if you still have an issue!
